In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\zaiid\OneDrive\Desktop\ironhack_final\netflix\netflix_titles.csv")

In [3]:
df.dropna(inplace = True)

In [4]:
df2 = pd.read_csv(r"C:\Users\zaiid\OneDrive\Desktop\ironhack_final\netflix\netflix_titles1.csv")

In [5]:
df2.dropna(inplace = True)

In [6]:
netflix_titles = pd.concat([df, df2])

In [7]:
netflix_titles

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
7,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
9,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [8]:
df.country.value_counts()

country
United States                  1323
India                           707
United Kingdom                  152
Canada                           78
Spain                            72
                               ...
South Korea, Czech Republic       1
Spain, France, Uruguay            1
Chile, Argentina                  1
Czech Republic, Slovakia          1
United Kingdom, Russia            1
Name: count, Length: 433, dtype: int64

In [9]:
netflix_titles.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [10]:
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Kids' TV"), 'listed_in'] = "Kids' TV"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Children & Family Movies|Music & Musicals"), 'listed_in'] = "Children & Family Movies"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Stand-Up Comedy"), 'listed_in'] = "Stand-Up Comedy"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Comedies, Horror Movies"), 'listed_in'] = "Comedies, Horror Movies"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("LGBTQ"), 'listed_in'] = "LGBTQ Movies"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Comedies") & netflix_titles['listed_in'].str.contains("Dramas"), 'listed_in'] = "Comedies, Dramas"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Dramas") & ~netflix_titles['listed_in'].str.contains("Comedies"), 'listed_in'] = "Dramas"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Comedies") & ~netflix_titles['listed_in'].str.contains("Dramas"), 'listed_in'] = "Comedies"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Horror Movies|TV Horror|Horror"), 'listed_in'] = "Horror"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Romantic Movies|Romantic TV Shows|Anime Features"), 'listed_in'] = "Romantic Movies"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Action & Adventure|Action|Sci-Fi & Fantasy"), 'listed_in'] = "Action"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Documentaries|Docuseries"), 'listed_in'] = "Documentaries"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("Thrillers"), 'listed_in'] = "Thrillers"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("TV Shows|Reality TV"), 'listed_in'] = "TV Shows"
netflix_titles.loc[netflix_titles['listed_in'].str.contains("International Movies|Independent Movies"), 'listed_in'] = "Movies"

In [11]:
netflix_titles

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,Children & Family Movies,Before planning an awesome wedding for his gra...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,Action,"In a dystopian future, an insurance adjuster f..."
7,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
9,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,Action,A struggling couple can't believe their luck w...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,Dramas,Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,Dramas,"A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,Comedies,Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,Children & Family Movies,"Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,Children & Family Movies,A scrappy but poor boy worms his way into a ty...

In [12]:
netflix_titles["rating"].value_counts()

rating
TV-MA       3011
TV-14       2131
R           1279
TV-PG        789
PG-13        748
PG           451
NR           233
TV-G         138
TV-Y7        124
TV-Y         100
G             75
TV-Y7-FV      14
UR            10
NC-17          3
Name: count, dtype: int64

In [13]:
rating_mapping = {
    'TV-MA': 'Mature',
    'TV-14': 'Teen',
    'R': 'Mature',
    'TV-PG': 'Family',
    'PG-13': 'Teen',
    'PG': 'Family',
    'NR': 'Unrated',
    'TV-G': 'Family',
    'TV-Y7': 'Children',
    'TV-Y': 'Children',
    'G': 'Family',
    'TV-Y7-FV': 'Children',
    'UR': 'Unrated',
    'NC-17': 'Mature'
}
netflix_titles['rating'] = netflix_titles['rating'].map(rating_mapping)

In [13]:
netflix_titles["country"] = netflix_titles["country"].replace("United Kingdom,", "United Kingdom")

In [14]:
netflix_titles = netflix_titles.drop_duplicates()

In [15]:
netflix_titles.reset_index(drop = True, inplace = True)

In [16]:
value_counts = netflix_titles['listed_in'].value_counts()
percentages = (value_counts / len(netflix_titles)) * 100


print("Percentages of each category in 'listed_in' column:\n", percentages)

Percentages of each category in 'listed_in' column:
 listed_in
Dramas                      31.352954
Comedies                    14.572809
Children & Family Movies    13.880958
Comedies, Dramas             8.401054
Action                       7.204041
Documentaries                5.996047
Stand-Up Comedy              5.963101
Horror                       5.776411
Thrillers                    2.591698
Romantic Movies              1.790029
LGBTQ Movies                 1.350758
Movies                       0.483198
TV Shows                     0.384362
Kids' TV                     0.252581
Name: count, dtype: float64

In [17]:
value_counts = netflix_titles['rating'].value_counts()
percentages = (value_counts / len(netflix_titles)) * 100
percentages

rating
Mature      47.144740
Teen        31.616517
Family      15.956512
Unrated      2.668570
Children     2.613661
Name: count, dtype: float64

In [18]:
netflix_titles['release_year'].value_counts()

release_year
2017    1242
2018    1185
2016    1091
2019     845
2015     673
        ...
1966       2
1945       2
1959       2
1961       1
1963       1
Name: count, Length: 72, dtype: int64

In [19]:
netflix_titles['date_added'].value_counts()

date_added
January 1, 2020      197
November 1, 2019     140
March 1, 2018        137
December 31, 2019    128
October 1, 2018      121
                    ...
February 8, 2021       1
February 13, 2021      1
February 14, 2021      1
February 15, 2021      1
April 18, 2020         1
Name: count, Length: 1499, dtype: int64

In [20]:

#netflix_titles['date_added'] = netflix_titles['date_added'].str.strip()
#netflix_titles['date_added'] = pd.to_datetime(netflix_titles['date_added'], format='%B %d, %Y')
#netflix_titles['date_added'] = netflix_titles['date_added'].dt.strftime('%B %Y')

In [21]:
netflix_titles.date_added.value_counts()

date_added
January 1, 2020      197
November 1, 2019     140
March 1, 2018        137
December 31, 2019    128
October 1, 2018      121
                    ...
February 8, 2021       1
February 13, 2021      1
February 14, 2021      1
February 15, 2021      1
April 18, 2020         1
Name: count, Length: 1499, dtype: int64

In [22]:
netflix_titles.to_csv('netflix_tableau1.csv', index=False)

In [24]:
netflix_titles.country.value_counts()

country
United States                                  3169
India                                          1582
United Kingdom                                  336
Canada                                          185
Spain                                           163
                                               ...
United States, India, United Kingdom              1
India, United Kingdom, France, Qatar              1
Chile, Brazil                                     1
United States, Cambodia, Romania                  1
France, Canada, Italy, United States, China       1
Name: count, Length: 624, dtype: int64

In [29]:
netflix_titles.type.value_counts()

type
Movie      8863
TV Show     243
Name: count, dtype: int64

In [27]:
netflix_titles.shape

(9106, 12)

In [31]:
netflix_titles.show_id.nunique()

9106

In [32]:
netflix_titles

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,Family,90 min,Children & Family Movies,Before planning an awesome wedding for his gra...
1,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,Teen,99 min,Comedies,When nerdy high schooler Dani finally attracts...
2,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,Mature,110 min,Action,"In a dystopian future, an insurance adjuster f..."
3,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,Mature,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
4,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,Mature,90 min,Action,A struggling couple can't believe their luck w...
...,...,...,...,...,...,...,...,...,...,...,...,...
9101,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,Mature,96 min,Dramas,Recovering alcoholic Talal wakes up inside a s...
9102,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,Mature,158 min,Dramas,"A political cartoonist, a crime reporter and a..."
9103,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,Mature,88 min,Comedies,Looking to survive in a world taken over by zo...
9104,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,Family,88 min,Children & Family Movies,"Dragged from civilian life, a former superhero..."
9105,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,Teen,111 min,Children & Family Movies,A scrappy but poor boy worms his way into a ty...

In [36]:
netflix_titles["type"].value_counts()

type
Movie      8863
TV Show     243
Name: count, dtype: int64

In [38]:
netflix_titles.show_id.value_counts()

show_id
81145628    1
s4290       1
s4283       1
s4284       1
s4285       1
           ..
81048551    1
70137790    1
80012535    1
80090672    1
s8807       1
Name: count, Length: 9106, dtype: int64

In [47]:
netflix_titles.show_id.astype

<bound method NDFrame.astype of 0       81145628
1       80125979
2       70304989
3       80164077
4       70304990
          ...
9101       s8802
9102       s8803
9103       s8805
9104       s8806
9105       s8807
Name: show_id, Length: 9106, dtype: object>

In [ ]:
netflix_titles.show_id